openapi: 3.1.0
x-stoplight:
  id: 83teyinnn1py6
info:
  title: Curb API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  parameters:
    curb_place_type:
      name: curb_place_type
      in: query
      required: false
      schema:
        type: string
      description: '**Required with `curb_place_id`.** The type of curb place this aggregate applies to from the Curbs API: area, zone, space. '
    curb_place_id:
      name: curb_place_id
      in: query
      required: false
      schema:
        type: string
      description: '**Required with `curb_place_id`.** The type of curb place this aggregate applies to from the Curbs API: area, zone, space. '
    min_lat:
      name: min_lat
      in: query
      required: false
      schema:
        type: string
      description: 'Used to specify a latitude and longitude bounding box. Must be used together with `min_lng`, `max_lat`, and `max_lng`. If specified only return locations that intersect the supplied bounding box. This parameter is incompatible with `lat`, `lng`, and `radius`.'
    min_lng:
      name: min_lng
      in: query
      required: false
      schema:
        type: string
      description: 'Used to specify a latitude and longitude bounding box. Must be used together with `min_lat`, `max_lat`, and `max_lng`.  If specified only return locations that intersect the supplied bounding box. This parameter is incompatible with `lat`, `lng`, and `radius`.'
    max_lat:
      name: max_lat
      in: query
      required: false
      schema:
        type: string
      description: 'Used to specify a latitude and longitude bounding box. Must be used together with `min_lat`, `min_lng`, and `max_lng`.  If specified only return locations that intersect the supplied bounding box. This parameter is incompatible with `lat`, `lng`, and `radius`.'
    max_lng:
      name: max_lng
      in: query
      required: false
      schema:
        type: string
      description: 'Used to specify a latitude and longitude bounding box. Must be used together with `min_lat`, `min_lng`, and `max_lat`.  If specified only return locations that intersect the supplied bounding box. This parameter is incompatible with `lat`, `lng`, and `radius`.'
    lat:
      name: lat
      in: query
      required: false
      schema:
        type: string
      description: 'Specifies a latitude and longitude bounding point and a radius away from that point. Must be used together with `lng` and `radius`. Returns only locations that are within radius centimeters of the point identified by lat/lng. Curb Zones in the response MUST be ordered ascending by distance from the center point. This parameter is incompatible with `min_lat`, `min_lng`, `max_lat`, and `max_lng`'
    lng:
      name: lng
      in: query
      required: false
      schema:
        type: string
      description: 'Specifies a latitude and longitude bounding point and a radius away from that point. Must be used together with `lat` and `radius`. Returns only locations that are within radius centimeters of the point identified by lat/lng. Curb Zones in the response MUST be ordered ascending by distance from the center point. This parameter is incompatible with `min_lat`, `min_lng`, `max_lat`, and `max_lng`'
    radius:
      name: radius
      in: query
      required: false
      schema:
        type: string
      description: 'Specifies a latitude and longitude bounding point and a radius away from that point. Must be used together with `lng` and `lng`. Returns only locations that are within radius centimeters of the point identified by lat/lng. Curb Zones in the response MUST be ordered ascending by distance from the center point. This parameter is incompatible with `min_lat`, `min_lng`, `max_lat`, and `max_lng`'
    start_time:
      name: start_time
      in: query
      required: false
      schema:
        type: string
      description: The start of the time period to return data where the value is inclusive.
    end_time:
      name: end_time
      in: query
      required: false
      schema:
        type: string
      description: The end of the time period to return data where the value is inclusive.
    curb_area_id:
      name: curb_area_id
      in: query
      required: false
      schema:
        type: string
      description: 'The ID of a Curb Area. If specified, only return records occurring within this area.'
    curb_zone_id:
      name: curb_zone_id
      in: query
      required: false
      schema:
        type: string
      description: 'The ID of a Curb Zone. If specified, only return records occurring within this zone.'
    curb_space_id:
      name: curb_space_id
      in: query
      required: false
      schema:
        type: string
      description: 'The ID of a Curb Space. If specified, only return records occurring within this area.'
